name = "biolinker"
compatibility_date = "2026-04-01"
main = "src/worker.ts"

[assets]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "cloudbio"
database_id = "local"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "local"

[[r2_buckets]]
binding = "R2"
bucket_name = "biolinker-uploads"
