name = "cloudbio"
compatibility_date = "2026-04-01"
main = "src/worker.ts"

[assets]
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "cloudbio"
database_id = "3b7f1c86-cb69-40a3-9a08-cefd05287146"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "a53dc755194d4990a6df0ed3b4148249"

[[r2_buckets]]
binding = "R2"
bucket_name = "cloudbio-r2"
